name: Build LaTeX document
on:
  push:
  schedule:
    - cron: '0 2 * * *'  # Run every day at 2 AM UTC

jobs:
  build_latex:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        texlive: [2023, 2024]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          texlive_version: ${{ matrix.texlive }}
          pre_compile: "tlmgr update --self && tlmgr update --all"
          root_file: main.tex
          post_compile: "latexmk -c"
          continue_on_error: false
          
      - uses: xu-cheng/latex-action@v3
        with:
          texlive_version: ${{ matrix.texlive }}
          root_file: main.tex
          latexmk_use_xelatex: true
          post_compile: "latexmk -c"
          continue_on_error: false
      
      - uses: xu-cheng/latex-action@v3
        with:
          texlive_version: ${{ matrix.texlive }}
          root_file: main.tex
          latexmk_shell_escape: true
          post_compile: "latexmk -c"
          continue_on_error: false

      - uses: xu-cheng/latex-action@v3
        with:
          texlive_version: ${{ matrix.texlive }}
          root_file: main.tex
          latexmk_use_lualatex: true
          post_compile: "latexmk -c"
          continue_on_error: false

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF-${{ matrix.os }}-texlive-${{ matrix.texlive }}
          path: main.pdf

      - id: get_version
        run:  echo "version=$(cat .version)" >> $GITHUB_OUTPUT
          
      - name: Create GitHub Release
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'Merge pull request')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: Release ${{ steps.get_version.outputs.version }}
          files: main.pdf
