name: Build LaTeX document
on:
  push:
  schedule:
    - cron: '0 2 * * *'  # Run every day at 2 AM UTC

jobs:
  build_latex:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        texlive: [2023, 2024]
    runs-on: ${{ matrix.os }}
    env:
      LATEX_ARGS: -pdf -file-line-error -halt-on-error -interaction=nonstopmode
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: XeLaTeX
        uses: jonaprieto/latex-action@v4
        with:
          texlive_version: ${{ matrix.texlive }}
          root_file: main.tex
          latexmk_use_xelatex: true
          post_compile: "latexmk -c"
          continue_on_error: false
          args: ${{ env.LATEX_ARGS }}
      
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF-${{ matrix.os }}-texlive-${{ matrix.texlive }}
          path: main.pdf

      - name: LuaLaTeX
        uses: jonaprieto/latex-action@v4
        with:
          texlive_version: ${{ matrix.texlive }}
          root_file: main.tex
          latexmk_use_lualatex: true
          post_compile: "latexmk -c"
          continue_on_error: false
          args: ${{ env.LATEX_ARGS }}

      - name: PdfLaTeX
        uses: jonaprieto/latex-action@v4
        with:
          texlive_version: ${{ matrix.texlive }}
          root_file: main.tex
          post_compile: "latexmk -c main.tex"
          continue_on_error: false
          args: ${{ env.LATEX_ARGS }}

      - id: get_version
        run:  echo "version=$(cat .version)" >> $GITHUB_OUTPUT
          
      - name: Create GitHub Release
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'Merge pull request')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: Release ${{ steps.get_version.outputs.version }}
          files: main.pdf
